### ISSUE TITLE
Block USB mice

### ISSUE THREAD

**Issue by jdgregson** [JLospinoso/beamgun#17]
Beambun does not react to the insertion of USB mice, and it is feasible for a bad USB device to emulate one. If the bad USB were to present itself as a mouse first, it could open the Beamgun window and click 'Exit' before enabling its keyboard capabilities. I can think of a few countermeasures for this:

1. Lock the workstation on mouse insertions
2. Lock the workstation whenever ANY USB device is inserted (except those on the future whitelist)
3. Place the Exit button in a semi-random location
4. Password-protect the Exit button

1 or 2 would probably be the most effective.

**Comment by JLospinoso** [comment]
@jdgregson I think this is an interesting enhancement. Want to give it a try?

**Comment by jdgregson** [comment]
I have it implemented and it works really well. I'm currently trying to figure out how to cram the "Lock on mouse" option into the GUI since it gets too busy. Most likely I'll add the checkboxes to a pupup menu.

**Comment by jdgregson** [comment]
This has been implemented in my MouseWatcher branch: https://github.com/jdgregson/beamgun/tree/MouseWatcher.

**Comment by jdgregson** [comment]
Support for locking on mouse insertion added in commit 7bae8ad.
